### ISSUE TITLE
My Idea

### ISSUE THREAD

**Issue by strangeide** [gta-chaos-mod/ChaosModComplementaries#3]
When the Timelapse Mode and the Faster Clock effect are enabled, the player's health and fat are no longer taken away
![1](https://user-images.githubusercontent.com/115400634/194751725-bff3f11f-3a34-4791-beea-0f2404d673de.png)

![2](https://user-images.githubusercontent.com/115400634/194751958-d7f9b9b9-6700-4010-ac00-b584753d554d.png)

![3](https://user-images.githubusercontent.com/115400634/194752019-2bd001d3-24c5-478e-badb-ed1c6ee08321.png)

![4](https://user-images.githubusercontent.com/115400634/194753115-a47a03ad-2bba-4c29-9276-8a6302f56f7f.png)

**Comment by strangeide** [comment]
And it's annoying when the Skinny Player effect is activated and if Timelapse Mode or Faster Clock is activated then your health will simply decrease

**Comment by Lordmau5** [comment]
1. This isn't the repo to post issues Chaos Mod effects
2. When CJ is hungry then he will lose health every in-game hour. If you do "Skinny Player" while CJ is hungry then he will start losing health directly afterwards. As for why it doesn't do it when you get "Fat Player" - I am only calling the internal cheat function and it could be that it also resets CJ's hunger when it get's enabled.

**Comment by strangeide** [comment]
> 1. This isn't the repo to post issues Chaos Mod effects
> 2. When CJ is hungry then he will lose health every in-game hour. If you do "Skinny Player" while CJ is hungry then he will start losing health directly afterwards. As for why it doesn't do it when you get "Fat Player" - I am only calling the internal cheat function and it could be that it also resets CJ's hunger when it get's enabled.

1. It's not problem
2. So what is the problem with disabling it?

**Comment by Lordmau5** [comment]
What do you mean "What is the problem with disabling it"? If you don't want to lose health make sure you also get the effect "Never Get Hungry" or an Infinite Health effect.
